sudo: false
language: rust
rust:
- 1.22.0 # oldest supported version
- stable
- beta
- nightly

install:
- rustc -Vv
- cargo -V

script:
- cargo check --verbose
- cargo test --verbose
- cargo doc --no-deps

cache:
  cargo: true
