sudo: false
language: rust
rust:
- 1.22.0 # oldest supported version
- stable
- beta
- nightly

matrix:
  include:
  - env: RUSTFMT
    rust: 1.27.0  # `stable`: Locking down for consistent behavior
    install:
    - rustup component add rustfmt-preview
    script:
    - cargo fmt --all -- --write-mode=diff
  - env: RUSTFLAGS="-D warnings"
    rust: 1.27.0  # `stable`: Locking down for consistent behavior
    script:
    - cargo check --all --tests
  - env: CLIPPY
    rust: nightly-2018-07-17
    install:
      - rustup component add clippy-preview
    script:
      - cargo clippy --all --all-features -- -D clippy

install:
- rustc -Vv
- cargo -V

script:
- cargo check --verbose --no-default-features
- cargo check --all --verbose
- cargo test --all --verbose
- cargo doc --all --no-deps

cache:
  cargo: true
